env:
  global:
    - CC_TEST_REPORTER_ID=bd8bdc104b6bce68936f368c8a13ccf3013f5e9acbe0d0a45758416f6f29f9db

language: php
dist: bionic

matrix:
  fast_finish: true
  include:
    - php: "7.0"
      env: TYPO3_VERSION=^8
    - php: "7.1"
      env: TYPO3_VERSION=^8
    - php: "7.2"
      env: TYPO3_VERSION=^9
    - php: "7.3"
      env: TYPO3_VERSION=^9

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms-core=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/Build/web
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - find . -name \*.php  ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - .Build/bin/phpunit -c Tests/UnitTests.xml --coverage-text --coverage-clover .Build/logs/clover.xml
  - ./cc-test-reporter format-coverage -t clover -o .Build/logs/codeclimate.json .Build/logs/clover.xml
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage -i .Build/logs/codeclimate.json; fi
