<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "byt_coordconverter"
 *
 * Auto generated by Extension Builder 2013-12-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Coordinate Converter',
    'description' => 'View helper for converting geospatial coordinates from one format into another',
    'category' => 'fe',
    'author' => 'Chris Müller',
    'author_email' => 'byt3error@web.de',
    'author_company' => '',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0.1',
    'constraints' => array(
        'depends' => array(
            'fluid' => '6.0.0-6.1.99',
            'typo3' => '6.0.0-6.1.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>